In [1]:
from sklearn import preprocessing
import numpy as np

c:\Users\acasa\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
# Carga de datos.
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [3]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
X_train_norm = normalizer.fit_transform(X_train)

In [4]:
# Salida de resultados.
print(X_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [5]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
X_train_2 = np.copy(X_train)

# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = normalizer.fit(X_train)

# Aplica el objeto sobre los datos "X_train_2" para obtener "X_train_norm_2"
X_train_norm_2 = f.transform(X_train)

# Comprueba si "X_train_norm" y "X_train_norm_2" son iguales
print(np.array_equiv(X_train_norm, X_train_norm_2))

True


In [9]:
# Normalizar un nuevo conjunto de datos de test (SOLO HAY QUE APLICAR EL MÉTODO "transform", NO EL "fit")
X_test = np.array([[ 1., -3.,  2.],
                    [ 3.,  0.,  0.],
                    [ 0.,  7., -1.]])

# Normalizar los datos de "X_test"
x_train_norm3 = f.transform(X_test)

display(x_train_norm3)

array([[0.2  , 0.1  , 0.625],
       [0.6  , 0.4  , 0.375],
       [0.   , 1.1  , 0.25 ]])