In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
# Carga de datos
X_train = [[1,      4], 
           [np.nan, 3], 
           [7,      8]]

In [4]:
# Limpieza de datos: imputación valores ausentes (modelo)
imputer = SimpleImputer(strategy='mean') # Utilizamos la estrategia de la media

# Aplicar los métodos "fit" y "transform" para imputar los valores pérdidos de X_train
X_train_clean = imputer.fit_transform(X_train)
print(X_train_clean)

[[1. 4.]
 [4. 3.]
 [7. 8.]]


In [5]:
# Imputación de valores ausentes sobre el conjunto de test
X_test = [[np.nan, 10], 
          [6,      np.nan], 
          [8,      2]]

# Imputar los datos del conjunto de test
X_test_clean = imputer.transform(X_test)
print(X_test_clean)

[[ 4. 10.]
 [ 6.  5.]
 [ 8.  2.]]


# Ejemplo Pinguinos

In [3]:
import pandas as pd
import numpy as np
from os import path
from sklearn.impute import SimpleImputer

In [4]:
csv = path.join('res','penguins.csv')
csv = pd.read_csv(csv, sep=';')

#csv = pd.read_csv('.\res\penguins.csv', sep = ';')

In [5]:
data = np.array(csv)
print(data)

[[3.910e+01 1.870e+01 1.810e+02 3.750e+03 0.000e+00]
 [3.950e+01 1.740e+01 1.860e+02 3.800e+03 0.000e+00]
 [4.030e+01 1.800e+01 1.950e+02 3.250e+03 0.000e+00]
 ...
 [4.960e+01 1.820e+01 1.930e+02 3.775e+03 2.000e+00]
 [5.080e+01 1.900e+01 2.100e+02 4.100e+03 2.000e+00]
 [5.020e+01 1.870e+01 1.980e+02 3.775e+03 2.000e+00]]


In [7]:
pos_ausentes= np.unique(np.where(np.isnan(data))[0])
print(pos_ausentes)

[]


In [8]:
# Limpieza de datos: imputación valores ausentes (modelo)
imputer = SimpleImputer(strategy='mean') # Utilizamos la estrategia de la media

# Aplicar los métodos "fit" y "transform" para imputar los valores pérdidos de X_train
data_clean = imputer.fit_transform(data)
print(data_clean)

[[3.910e+01 1.870e+01 1.810e+02 3.750e+03 0.000e+00]
 [3.950e+01 1.740e+01 1.860e+02 3.800e+03 0.000e+00]
 [4.030e+01 1.800e+01 1.950e+02 3.250e+03 0.000e+00]
 ...
 [4.960e+01 1.820e+01 1.930e+02 3.775e+03 2.000e+00]
 [5.080e+01 1.900e+01 2.100e+02 4.100e+03 2.000e+00]
 [5.020e+01 1.870e+01 1.980e+02 3.775e+03 2.000e+00]]


In [13]:
pos_ausentes= np.unique(np.where(np.isnan(data_clean))[0])
print(pos_ausentes)

[]


In [18]:
df = pd.DataFrame(data_clean, columns = ["Culmen length","Culmen depth","Flipper length","Body mass","Especies"])
df.to_csv('./res/penguins_clean.csv', sep=';', index=False)